name: unit-test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: true
      NODE_ENV: test
      # Added alignment for clarity.
      # Firebase client credentials.
      NEXT_PUBLIC_FIREBASE_API_KEY            : ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        : ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID         : ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     : ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID             : ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID     : ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      # Firebase admin credentials.
      FIREBASE_ADMIN_PROJECT_ID               : ${{ secrets.FIREBASE_ADMIN_PROJECT_ID }}
      FIREBASE_ADMIN_PRIVATE_KEY              : ${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
      FIREBASE_ADMIN_CLIENT_EMAIL             : ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
      # Firestore credentials.
      FIRESTORE_CONFIG_COLLECTION_ID          : ${{ secrets.FIRESTORE_CONFIG_COLLECTION_ID }}
      FIRESTORE_ADMIN_DOCUMENT_ID             : ${{ secrets.FIRESTORE_ADMIN_DOCUMENT_ID }}
      FIRESTORE_ADMIN_EMAIL_ARRAY_FIELDNAME   : ${{ secrets.FIRESTORE_ADMIN_EMAIL_ARRAY_FIELDNAME }}
      # Stack Auth credentials.
      NEXT_PUBLIC_STACK_PROJECT_ID            : ${{ secrets.NEXT_PUBLIC_STACK_PROJECT_ID }}
      NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
      STACK_SECRET_SERVER_KEY                 : ${{ secrets.STACK_SECRET_SERVER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm before node
        # Pinned to commit hash of release v4.0.0 on 05/07/24.
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        # Omit with to use package.json packageManager field pnpm version.

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: CI lint
        run: pnpm lint

      - name: Test build
        run: pnpm build

      - name: Unit test
        run: pnpm test:unit
